export interface Course {
  id: string;
  title_ar: string;
  title_en: string;
  lecturer_ar: string;
  lecturer_en: string;
  specialty_ar: string;
  specialty_en: string;
  students: number;
  rating: number;
  price: number;
  status: 'active' | 'paused';
  lastUpdate_ar: string;
  lastUpdate_en: string;
}

export const MOCK_COURSES: Course[] = [
  {
    id: '1',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'active',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '2',
    title_ar: 'علم الاعصاب السريري',
    title_en: 'Clinical Neurology',
    lecturer_ar: 'د. سارة خليل',
    lecturer_en: 'Dr. Sara Khalil',
    specialty_ar: 'طب الاعصاب',
    specialty_en: 'Neurology',
    students: 1245,
    rating: 4.8,
    price: 249,
    status: 'active',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '3',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'active',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '4',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'paused',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '5',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'active',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '6',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'active',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '7',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'active',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '8',
    title_ar: 'اساسيات امراض القلب',
    title_en: 'Cardiology Basics',
    lecturer_ar: 'د. احمد محمود',
    lecturer_en: 'Dr. Ahmed Mahmoud',
    specialty_ar: 'امراض القلب',
    specialty_en: 'Cardiology',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: 'paused',
    lastUpdate_ar: '27 أغسطس 2026',
    lastUpdate_en: '27 August 2026',
  },
  {
    id: '9',
    title_ar: 'علم الاعصاب السريري',
    title_en: 'Clinical Neurology',
    lecturer_ar: 'د. سارة خليل',
    lecturer_en: 'Dr. Sara Khalil',
    specialty_ar: 'طب الاعصاب',
    specialty_en: 'Neurology',
    students: 950,
    rating: 4.5,
    price: 249,
    status: 'active',
    lastUpdate_ar: '25 أغسطس 2026',
    lastUpdate_en: '25 August 2026',
  },
  {
    id: '10',
    title_ar: 'مقدمة في طب الطوارئ',
    title_en: 'Emergency Medicine',
    lecturer_ar: 'د. خالد العتيبي',
    lecturer_en: 'Dr. Khaled Al-Otaibi',
    specialty_ar: 'طب الطوارئ',
    specialty_en: 'Emergency Medicine',
    students: 800,
    rating: 4.7,
    price: 120,
    status: 'active',
    lastUpdate_ar: '20 أغسطس 2026',
    lastUpdate_en: '20 August 2026',
  },
  {
    id: '11',
    title_ar: 'أساسيات الجراحة العامة',
    title_en: 'General Surgery Basics',
    lecturer_ar: 'د. محمد علي',
    lecturer_en: 'Dr. Mohamed Ali',
    specialty_ar: 'جراحة عامة',
    specialty_en: 'General Surgery',
    students: 1500,
    rating: 4.9,
    price: 300,
    status: 'active',
    lastUpdate_ar: '15 أغسطس 2026',
    lastUpdate_en: '15 August 2026',
  },
  {
    id: '12',
    title_ar: 'طب الأطفال الشامل',
    title_en: 'Pediatric Care',
    lecturer_ar: 'د. فاطمة الزهراء',
    lecturer_en: 'Dr. Fatima Zahra',
    specialty_ar: 'طب الأطفال',
    specialty_en: 'Pediatrics',
    students: 1100,
    rating: 4.6,
    price: 180,
    status: 'paused',
    lastUpdate_ar: '10 أغسطس 2026',
    lastUpdate_en: '10 August 2026',
  },
];
