import {
  KpiCardItem,
  NeedsAttentionItem,
  AcademicStructureData,
  CourseBreakdownItem,
  TopCourseItem,
  LatestUserItem,
  RecentActivityItem,
} from './types';

export const MOCK_KPIS: KpiCardItem[] = [
  {
    id: 'students',
    titleKey: 'total_students',
    value: '12,450',
    change: '+8.5%',
    isPositive: true,
    subtitleKey: 'vs_last_month',
    icon: 'solar:users-group-two-rounded-bold',
    iconBg: '#EFF6FF',
    iconColor: '#3B82F6',
  },
  {
    id: 'lecturers',
    titleKey: 'total_lecturers',
    value: '320',
    change: '+5.2%',
    isPositive: true,
    subtitleKey: 'vs_last_month',
    icon: 'solar:user-id-bold',
    iconBg: '#EFF6FF',
    iconColor: '#3B82F6',
  },
  {
    id: 'courses',
    titleKey: 'total_courses',
    value: '856',
    change: '+12.4%',
    isPositive: true,
    subtitleKey: 'vs_last_month',
    icon: 'solar:square-academic-cap-bold',
    iconBg: '#EFF6FF',
    iconColor: '#3B82F6',
  },
  {
    id: 'published',
    titleKey: 'published_courses',
    value: '742',
    change: '+9.8%',
    isPositive: true,
    subtitleKey: 'active_now_for_students',
    icon: 'solar:check-circle-bold',
    iconBg: '#ECFDF5',
    iconColor: '#10B981',
  },
  {
    id: 'under_review',
    titleKey: 'under_review_courses',
    value: '24',
    badge: 'needs_audit',
    badgeColor: '#DC2626',
    badgeBg: '#FEF2F2',
    valueColor: '#DC2626',
    subBadge: 'action_required',
    subBadgeBg: '#991B1B',
    subBadgeColor: '#FFFFFF',
    icon: 'solar:document-medicine-bold',
    iconBg: '#FEF2F2',
    iconColor: '#EF4444',
  },
  {
    id: 'orders',
    titleKey: 'total_orders',
    value: '18,920',
    change: '+10.3%',
    isPositive: true,
    subtitleKey: 'vs_last_month',
    icon: 'solar:bag-bold',
    iconBg: '#EFF6FF',
    iconColor: '#3B82F6',
  },
];

export const MOCK_NEEDS_ATTENTION: NeedsAttentionItem[] = [
  {
    id: 'courses_review',
    count: 24,
    circleBg: '#FEE2E2',
    circleColor: '#DC2626',
    titleKey: 'card_1.title',
    descKey: 'card_1.description',
    actionKey: 'card_1.action',
    actionHref: '/courses?status=pending',
    badgeKey: 'card_1.badge',
    badgeColor: '#DC2626',
    btnBg: '#1C252E',
    btnColor: '#FFFFFF',
    btnHoverBg: '#2C353E',
  },
  {
    id: 'new_lecturers',
    count: 18,
    circleBg: '#DBEAFE',
    circleColor: '#2563EB',
    titleKey: 'card_2.title',
    descKey: 'card_2.description',
    actionKey: 'card_2.action',
    actionHref: '/minutes-management',
    badgeKey: 'card_2.badge',
    badgeColor: '#92400E',
    btnBg: '#EFF6FF',
    btnColor: '#2563EB',
    btnHoverBg: '#DBEAFE',
  },
  {
    id: 'rejected_courses',
    count: 7,
    circleBg: '#F1F5F9',
    circleColor: '#475569',
    titleKey: 'card_3.title',
    descKey: 'card_3.description',
    actionKey: 'card_3.action',
    actionHref: '/courses?status=rejected',
    badgeKey: 'card_3.badge',
    badgeColor: '#64748B',
    btnBg: '#F1F5F9',
    btnColor: '#475569',
    btnHoverBg: '#E2E8F0',
  },
];

export const MOCK_ACADEMIC_STRUCTURE: AcademicStructureData = {
  countries: 12,
  universities: 48,
  colleges: 86,
  subjects: 214,
  activeCourses: 856,
};

export const MOCK_STUDENTS_CHART = {
  categoriesAr: ['يناير', 'مارس', 'مايو', 'يوليو', 'سبتمبر', 'نوفمبر', 'ديسمبر (الحالي)'],
  categoriesEn: ['Jan', 'Mar', 'May', 'Jul', 'Sep', 'Nov', 'Dec (Current)'],
  series: [
    {
      name: 'الطلاب الجدد',
      nameEn: 'New Students',
      data: [350, 480, 560, 680, 740, 810, 840],
    },
  ],
};

export const MOCK_COURSES_BREAKDOWN: CourseBreakdownItem[] = [
  { id: 'published', labelKey: 'published', count: 742, percentage: 86.6, color: '#10B981' },
  { id: 'in_review', labelKey: 'in_review', count: 24, percentage: 2.8, color: '#2563EB' },
  { id: 'drafts', labelKey: 'drafts', count: 51, percentage: 6.0, color: '#F59E0B' },
  { id: 'rejected', labelKey: 'rejected', count: 27, percentage: 3.1, color: '#EF4444' },
  { id: 'paused', labelKey: 'paused', count: 12, percentage: 1.5, color: '#64748B' },
];

export const MOCK_SALES_SUMMARY = {
  totalRevenue: '125,000',
  completedOrders: '17,850',
  pendingOrders: 420,
  monthlyBars: [
    { month: 'يوليو', monthEn: 'Jul', fill: '#DBEAFE', height: 40 },
    { month: 'أغسطس', monthEn: 'Aug', fill: '#DBEAFE', height: 50 },
    { month: 'سبتمبر', monthEn: 'Sep', fill: '#BFDBFE', height: 65 },
    { month: 'أكتوبر', monthEn: 'Oct', fill: '#93C5FD', height: 80 },
    { month: 'نوفمبر', monthEn: 'Nov', fill: '#1E3A8A', height: 95 },
    { month: 'ديسمبر', monthEn: 'Dec', fill: '#0F172A', height: 100, active: true },
  ],
};

export const MOCK_TOP_COURSES: TopCourseItem[] = [
  {
    id: 'c-1',
    course_name: 'أساسيات أمراض القلب',
    lecturer: 'د . أحمد محمود',
    specialty: 'أمراض القلب',
    students: 1245,
    rating: 4.8,
    price: 150,
    status: true,
    last_update: '27 أغسطس 2026',
  },
  {
    id: 'c-2',
    course_name: 'أساسيات أمراض القلب',
    lecturer: 'د . أحمد محمود',
    specialty: 'أمراض القلب',
    students: 1000,
    rating: 4.8,
    price: 150,
    status: true,
    last_update: '27 أغسطس 2026',
  },
  {
    id: 'c-3',
    course_name: 'أساسيات أمراض القلب',
    lecturer: 'د . أحمد محمود',
    specialty: 'أمراض القلب',
    students: 870,
    rating: 4.8,
    price: 150,
    status: true,
    last_update: '27 أغسطس 2026',
  },
  {
    id: 'c-4',
    course_name: 'أساسيات أمراض القلب',
    lecturer: 'د . أحمد محمود',
    specialty: 'أمراض القلب',
    students: 870,
    rating: 4.8,
    price: 150,
    status: true,
    last_update: '27 أغسطس 2026',
  },
];

export const MOCK_LATEST_USERS: LatestUserItem[] = [
  {
    id: 'u-1',
    name: 'د. لمياء إبراهيم',
    role: 'lecturer',
    university: 'جامعة عين شمس • تشريح',
    avatar: 'https://images.unsplash.com/photo-1594824813593-90d0b04b95bb?w=120&auto=format&fit=crop&q=80',
    statusText: 'نشط',
    isActiveStatus: true,
  },
  {
    id: 'u-2',
    name: 'عمر فاروق',
    role: 'student',
    university: 'جامعة القاهرة • السنة الرابعة',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    statusText: 'منذ 2 س',
    isActiveStatus: false,
  },
  {
    id: 'u-3',
    name: 'د. سارة محمود',
    role: 'lecturer',
    university: 'جامعة الإسكندرية • جراحة',
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=120&auto=format&fit=crop&q=80',
    statusText: 'نشط',
    isActiveStatus: true,
  },
  {
    id: 'u-4',
    name: 'نوران شريف',
    role: 'student',
    university: 'جامعة المنصورة • السنة الخامسة',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    statusText: 'اليوم',
    isActiveStatus: false,
  },
];

export const MOCK_RECENT_ACTIVITIES: RecentActivityItem[] = [
  {
    id: 'act-1',
    type: 'submit',
    titleAr: 'تم إرسال دورة «أساسيات أمراض القلب» للمراجعة بواسطة د. أحمد محمد علي',
    titleEn: 'Course «Cardiology Basics» submitted for review by Dr. Ahmed Mohamed Ali',
    timeAr: 'منذ 15 دقيقة',
    timeEn: '15 minutes ago',
    icon: 'solar:document-text-bold',
    iconColor: '#2563EB',
    iconBg: '#EFF6FF',
  },
  {
    id: 'act-2',
    type: 'approve',
    titleAr: 'تمت الموافقة على دورة «تخطيط القلب ECG» ونشرها رسمياً بواسطة مدير النظام',
    titleEn: 'Course «ECG Basics» approved and published officially by System Admin',
    timeAr: 'منذ ساعتين',
    timeEn: '2 hours ago',
    icon: 'solar:check-circle-bold',
    iconColor: '#10B981',
    iconBg: '#ECFDF5',
  },
  {
    id: 'act-3',
    type: 'register_student',
    titleAr: 'تسجيل طالب جديد: عمر فاروق – كلية الطب – جامعة القاهرة',
    titleEn: 'New student enrolled: Omar Farouk – Faculty of Medicine – Cairo University',
    timeAr: 'منذ 3 ساعات',
    timeEn: '3 hours ago',
    icon: 'solar:users-group-two-rounded-bold',
    iconColor: '#3B82F6',
    iconBg: '#EFF6FF',
  },
  {
    id: 'act-4',
    type: 'new_lecturer',
    titleAr: 'تم إنشاء حساب محاضر جديد: د. لمياء إبراهيم (قسم التشريح والطب الشرعي)',
    titleEn: 'New lecturer registered: Dr. Lamiaa Ibrahim (Anatomy & Forensic Medicine)',
    timeAr: 'اليوم 11:30 ص',
    timeEn: 'Today 11:30 AM',
    icon: 'solar:user-id-bold',
    iconColor: '#6366F1',
    iconBg: '#EEF2FF',
  },
  {
    id: 'act-5',
    type: 'reject',
    titleAr: 'تم رفض دورة غير مكتملة المعايير وإرسال سبب الرفض والملاحظات للمحاضر للتعديل',
    titleEn: 'Course rejected for incomplete criteria with feedback sent to lecturer',
    timeAr: 'أمس 04:15 م',
    timeEn: 'Yesterday 04:15 PM',
    icon: 'solar:close-circle-bold',
    iconColor: '#EF4444',
    iconBg: '#FEF2F2',
  },
];
