import {
  InstructorProfile,
  InstructorCourseItem,
  InstructorSubscriptionRequest,
  InstructorReviewItem,
} from 'src/types/instructor';

export const MOCK_INSTRUCTOR_PROFILE: InstructorProfile = {
  id: 'inst-1',
  name: 'د. علي محمد',
  title: 'استشاري أمراض الباطنة والجهاز الهضمي والمناظير',
  specialty: 'أمراض الباطنة والجهاز الهضمي',
  avatarInitials: 'ع م',
  isActive: true,
  rating: 4.8,
  ratingCount: 340,
  joinedDate: '05-08-2026',
  email: 'alimoha.e@gmail.com',
  phoneNumber: '35 5432 9876',
  country: 'الكويت',
  university: 'جامعة الكويت',
  qualification: 'دكتوراه في الطب والجراحة',
  bio: 'استشاري أول أمراض الباطنة والجهاز الهضمي والمناظير التداخلية المتقدمة، زميل الكلية الملكية للأطباء والجراحين. يمتلك خبرة تتجاوز 15 عاماً في التدريس الأكاديمي، إعداد المناهج الطبية المعتمدة وتدريب أطباء البورد والزمالة الطبية في الكويت والخليج العربي.',
  totalCourses: 6,
  activeCourses: 4,
  totalStudents: 1240,
  studentsGrowth: '+15% هذا الشهر',
  trainingHours: 84,
  totalSales: 18500,
  currency: 'د.ك',
  satisfactionRate: 96,
};

export const MOCK_INSTRUCTORS_LIST: InstructorProfile[] = [
  MOCK_INSTRUCTOR_PROFILE,
  {
    id: 'inst-2',
    name: 'د. شريف حلمي',
    title: 'استشاري أمراض القلب والأوعية الدموية وقسطرة القلب',
    specialty: 'أمراض القلب والقسطرة',
    avatarInitials: 'ش ح',
    isActive: true,
    rating: 4.9,
    ratingCount: 420,
    joinedDate: '12-07-2026',
    email: 'sherif.helmy@cardio.med',
    phoneNumber: '+965 4123 9988',
    country: 'الكويت',
    university: 'جامعة الكويت',
    qualification: 'دكتوراه أمراض القلب والأوعية الدموية',
    bio: 'استشاري قسطرة القلب التداخلية، عضو جمعية القلب الأمريكية. قام بتدريب أكثر من 1,000 طبيب مقيم ومتدرب في برامج الزمالة.',
    totalCourses: 5,
    activeCourses: 5,
    totalStudents: 1560,
    studentsGrowth: '+22% هذا الشهر',
    trainingHours: 110,
    totalSales: 24200,
    currency: 'د.ك',
    satisfactionRate: 98,
  },
  {
    id: 'inst-3',
    name: 'د. محمود سالم',
    title: 'استشاري الجراحة العامة والمناظير وجراحة الأورام',
    specialty: 'الجراحة العامة',
    avatarInitials: 'م س',
    isActive: true,
    rating: 4.7,
    ratingCount: 290,
    joinedDate: '01-06-2026',
    email: 'm.salem@surgery.org',
    phoneNumber: '+965 5544 3322',
    country: 'جمهورية مصر العربية',
    university: 'جامعة القاهرة (القصر العيني)',
    qualification: 'دكتوراه الجراحة العامة والمناظير',
    bio: 'استشاري جراحة الأورام والمناظير المتقدمة، محاضر إكلينيكي ورئيس قسم التدريب الجراحي الأكاديمي.',
    totalCourses: 4,
    activeCourses: 3,
    totalStudents: 980,
    studentsGrowth: '+10% هذا الشهر',
    trainingHours: 65,
    totalSales: 14800,
    currency: 'د.ك',
    satisfactionRate: 94,
  },
  {
    id: 'inst-4',
    name: 'د. سارة عثمان',
    title: 'أستاذ الفارماكولوجي السريري والعلاج الدوائي المتقدم',
    specialty: 'الفارماكولوجي السريري',
    avatarInitials: 'س ع',
    isActive: false,
    rating: 4.6,
    ratingCount: 180,
    joinedDate: '20-05-2026',
    email: 'sara.osman@pharm.edu',
    phoneNumber: '+965 6677 8899',
    country: 'المملكة العربية السعودية',
    university: 'جامعة الملك سعود',
    qualification: 'دكتوراه في علم الأدوية السريري',
    bio: 'خبيرة العلاج الدوائي التداخلي وتعديل الجرعات الدوائية للمرضى ذوي الحالات الحرجة.',
    totalCourses: 3,
    activeCourses: 2,
    totalStudents: 620,
    studentsGrowth: '+5% هذا الشهر',
    trainingHours: 48,
    totalSales: 8900,
    currency: 'د.ك',
    satisfactionRate: 92,
  },
  {
    id: 'inst-5',
    name: 'د. يوسف التميمي',
    title: 'استشاري جراحة العظام والمفاصل والإصابات الرياضية',
    specialty: 'جراحة العظام والمفاصل',
    avatarInitials: 'ي ت',
    isActive: true,
    rating: 4.85,
    ratingCount: 310,
    joinedDate: '15-04-2026',
    email: 'y.altamimi@ortho.med',
    phoneNumber: '+965 9988 7766',
    country: 'الكويت',
    university: 'جامعة الكويت',
    qualification: 'دكتوراه جراحة العظام والعمود الفقري',
    bio: 'استشاري جراحة مناظير المفاصل والكسور المعقدة، زميل الكلية الملكية للأطباء والجراحين.',
    totalCourses: 4,
    activeCourses: 4,
    totalStudents: 850,
    studentsGrowth: '+18% هذا الشهر',
    trainingHours: 72,
    totalSales: 16400,
    currency: 'د.ك',
    satisfactionRate: 97,
  },
  {
    id: 'inst-6',
    name: 'د. منى عبد الرحمن',
    title: 'استشارية طب الأطفال وحديثي الولادة والعناية المركزة',
    specialty: 'طب الأطفال وحديثي الولادة',
    avatarInitials: 'م ع',
    isActive: false,
    rating: 4.75,
    ratingCount: 220,
    joinedDate: '01-03-2026',
    email: 'm.abdulrahman@pediatrics.org',
    phoneNumber: '+965 5511 2233',
    country: 'جمهورية مصر العربية',
    university: 'جامعة عين شمس',
    qualification: 'دكتوراه طب الأطفال والرعاية الحرجة',
    bio: 'استشارية العناية المركزة لحديثي الولادة، مدربة معتمدة في إنعاش الأطفال والولدان المتقدم.',
    totalCourses: 3,
    activeCourses: 1,
    totalStudents: 540,
    studentsGrowth: '+8% هذا الشهر',
    trainingHours: 40,
    totalSales: 7500,
    currency: 'د.ك',
    satisfactionRate: 95,
  },
];

export const MOCK_PUBLISHED_COURSES: InstructorCourseItem[] = [
  {
    id: 'crs-1',
    title: 'اساسيات امراض القلب',
    specialty: 'امراض القلب',
    studentsCount: 1245,
    rating: 4.8,
    price: 150,
    currency: 'د.ك',
    status: 'active',
    statusText: 'نشط',
    lastUpdated: '27 أغسطس 2026',
  },
  {
    id: 'crs-2',
    title: 'اساسيات امراض القلب',
    specialty: 'امراض القلب',
    studentsCount: 1245,
    rating: 4.8,
    price: 150,
    currency: 'د.ك',
    status: 'active',
    statusText: 'نشط',
    lastUpdated: '27 أغسطس 2026',
  },
  {
    id: 'crs-3',
    title: 'اساسيات امراض القلب',
    specialty: 'امراض القلب',
    studentsCount: 1245,
    rating: 4.8,
    price: 150,
    currency: 'د.ك',
    status: 'active',
    statusText: 'نشط',
    lastUpdated: '27 أغسطس 2026',
  },
  {
    id: 'crs-4',
    title: 'اساسيات امراض القلب',
    specialty: 'امراض القلب',
    studentsCount: 1245,
    rating: 4.8,
    price: 150,
    currency: 'د.ك',
    status: 'active',
    statusText: 'نشط',
    lastUpdated: '27 أغسطس 2026',
  },
  {
    id: 'crs-5',
    title: 'اساسيات امراض القلب',
    specialty: 'امراض القلب',
    studentsCount: 1245,
    rating: 4.8,
    price: 150,
    currency: 'د.ك',
    status: 'active',
    statusText: 'نشط',
    lastUpdated: '27 أغسطس 2026',
  },
  {
    id: 'crs-6',
    title: 'اساسيات امراض القلب',
    specialty: 'امراض القلب',
    studentsCount: 1245,
    rating: 4.8,
    price: 150,
    currency: 'د.ك',
    status: 'paused',
    statusText: 'متوقف',
    lastUpdated: '27 أغسطس 2026',
  },
];

export const MOCK_SUBSCRIPTION_REQUESTS: InstructorSubscriptionRequest[] = [
  {
    id: 'sub-1',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    studentPhone: '+9662 326261',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    requestDate: '8/9/2026',
    status: 'approved',
    statusText: 'مقبول',
    orderNumber: '#ORD-10245',
    amount: '150 د.ك',
  },
  {
    id: 'sub-2',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    studentPhone: '+9662 326261',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    requestDate: '8/9/2026',
    status: 'approved',
    statusText: 'مقبول',
    orderNumber: '#ORD-10246',
    amount: '150 د.ك',
  },
  {
    id: 'sub-3',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    studentPhone: '+9662 326261',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    requestDate: '8/9/2026',
    status: 'approved',
    statusText: 'مقبول',
    orderNumber: '#ORD-10247',
    amount: '150 د.ك',
  },
  {
    id: 'sub-4',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    studentPhone: '+9662 326261',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    requestDate: '8/9/2026',
    status: 'approved',
    statusText: 'مقبول',
    orderNumber: '#ORD-10248',
    amount: '150 د.ك',
  },
  {
    id: 'sub-5',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    studentPhone: '+9662 326261',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    requestDate: '8/9/2026',
    status: 'approved',
    statusText: 'مقبول',
    orderNumber: '#ORD-10249',
    amount: '150 د.ك',
  },
  {
    id: 'sub-6',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    studentPhone: '+9662 326261',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    requestDate: '8/9/2026',
    status: 'approved',
    statusText: 'مقبول',
    orderNumber: '#ORD-10250',
    amount: '150 د.ك',
  },
];

export const MOCK_INSTRUCTOR_REVIEWS: InstructorReviewItem[] = [
  {
    id: 'rev-1',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    courseRating: 5.0,
    courseComment: 'محتوى شامل ومنظم جداً واختبارات قياس المستوى ممتازة وساعدتني في التحضير للبورد.',
    instructorRating: 5.0,
    instructorComment: 'أسلوب د. علي في تبسيط تخطيط القلب المعقد رائع ورفع ثقتي جداً في تشخيص الحالات الإكلينيكية.',
    reviewDate: '9/9/2026',
  },
  {
    id: 'rev-2',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    courseRating: 5.0,
    courseComment: 'محتوى شامل ومنظم جداً واختبارات قياس المستوى ممتازة وساعدتني في التحضير للبورد.',
    instructorRating: 5.0,
    instructorComment: 'أسلوب د. علي في تبسيط تخطيط القلب المعقد رائع ورفع ثقتي جداً في تشخيص الحالات الإكلينيكية.',
    reviewDate: '9/9/2026',
  },
  {
    id: 'rev-3',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    courseRating: 5.0,
    courseComment: 'محتوى شامل ومنظم جداً واختبارات قياس المستوى ممتازة وساعدتني في التحضير للبورد.',
    instructorRating: 5.0,
    instructorComment: 'أسلوب د. علي في تبسيط تخطيط القلب المعقد رائع ورفع ثقتي جداً في تشخيص الحالات الإكلينيكية.',
    reviewDate: '9/9/2026',
  },
  {
    id: 'rev-4',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    courseRating: 5.0,
    courseComment: 'محتوى شامل ومنظم جداً واختبارات قياس المستوى ممتازة وساعدتني في التحضير للبورد.',
    instructorRating: 5.0,
    instructorComment: 'أسلوب د. علي في تبسيط تخطيط القلب المعقد رائع ورفع ثقتي جداً في تشخيص الحالات الإكلينيكية.',
    reviewDate: '9/9/2026',
  },
  {
    id: 'rev-5',
    studentName: 'د. سارة العتيبي',
    studentEmail: 's.alotaibi@med.edu',
    studentInitials: 'س ع',
    courseTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    courseCategory: 'قسم الباطنة',
    courseRating: 5.0,
    courseComment: 'محتوى شامل ومنظم جداً واختبارات قياس المستوى ممتازة وساعدتني في التحضير للبورد.',
    instructorRating: 5.0,
    instructorComment: 'أسلوب د. علي في تبسيط تخطيط القلب المعقد رائع ورفع ثقتي جداً في تشخيص الحالات الإكلينيكية.',
    reviewDate: '9/9/2026',
  },
];
