import type { InstructorAnalyticsData, StudentGrowthPoint } from './types';

const growthPoints: StudentGrowthPoint[] = [
  { month: 'أبريل', count: 156 },
  { month: 'مايو', count: 172 },
  { month: 'يونيو', count: 188 },
  { month: 'يوليو', count: 210 },
  { month: 'أغسطس', count: 246 },
  { month: 'سبتمبر', count: 286 },
];

export const INSTRUCTOR_ANALYTICS_MOCK: InstructorAnalyticsData = {
  kpis: {
    totalStudents: 286,
    studentsGrowthPercent: 12.4,
    activeCourses: 8,
    approvedCourses: 6,
    pendingReviewCourses: 2,
    completedLessons: 96,
    lessonsGrowthPercent: 18.0,
    netEarnings: 3680,
    earningsGrowthPercent: 14.2,
    instructorSharePercent: 70,
  },
  growth: {
    points: growthPoints,
    newStudentsThisMonth: 26,
    currentMonth: 'سبتمبر',
    currentGrowthPercent: 12.4,
    retentionRate: 94.2,
  },
  topCourses: [
    {
      id: '1',
      title: 'مادة التشريح',
      enrolledStudents: 42,
      completionPercent: 78,
      totalRevenue: 1240,
      instructorShare: 868,
      instructorSharePercent: 70,
      status: 'approved',
      progressColor: '#0052CC',
    },
    {
      id: '2',
      title: 'مادة التشريح',
      enrolledStudents: 31,
      completionPercent: 70,
      totalRevenue: 990,
      instructorShare: 693,
      instructorSharePercent: 70,
      status: 'approved',
      progressColor: '#003D99',
    },
    {
      id: '3',
      title: 'مادة الرمد',
      enrolledStudents: 27,
      completionPercent: 64,
      totalRevenue: 980,
      instructorShare: 686,
      instructorSharePercent: 70,
      status: 'pending_review',
      progressColor: '#FF9F1C',
    },
  ],
  financials: {
    grossRevenue: 5240.0,
    netInstructorShare: 3668.0,
    netInstructorPercent: 70,
    platformShare: 1572.0,
    platformPercent: 30,
    pendingPayouts: 420.0,
  },
  revenueSources: [
    {
      label: 'مبيعات الدورات المسجلة',
      amount: 3200.0,
      percent: 61,
      icon: 'solar:book-bookmark-bold',
    },
    {
      label: 'الدروس المباشرة الفردية',
      amount: 2040.0,
      percent: 39,
      icon: 'solar:videocamera-record-bold',
    },
  ],
  transactions: [
    {
      id: 'trx-1',
      dateTime: '26/09/2026 - 03:45 م',
      description: 'اشتراك دورة مادة التشريح',
      student: 'أحمد محمد',
      type: 'course',
      totalAmount: 240.0,
      instructorShare: 168.0,
      platformShare: 72.0,
      status: 'paid',
    },
    {
      id: 'trx-2',
      dateTime: '25/09/2026 - 09:20 م',
      description: 'حصة مباشرة فردية - 60 دقيقة',
      student: 'سارة حسام',
      type: 'lesson',
      totalAmount: 85.0,
      instructorShare: 59.5,
      platformShare: 25.5,
      status: 'paid',
    },
    {
      id: 'trx-3',
      dateTime: '24/09/2026 - 12:10 م',
      description: 'اشتراك دورة مادة الرمد',
      student: 'محمد سمير',
      type: 'course',
      totalAmount: 180.0,
      instructorShare: 126.0,
      platformShare: 54.0,
      status: 'pending',
    },
    {
      id: 'trx-4',
      dateTime: '23/09/2026 - 07:35 م',
      description: 'حصة مباشرة فردية - 45 دقيقة',
      student: 'نور الهدى عادل',
      type: 'lesson',
      totalAmount: 60.0,
      instructorShare: 42.0,
      platformShare: 18.0,
      status: 'pending',
    },
    {
      id: 'trx-5',
      dateTime: '22/09/2026 - 02:50 م',
      description: 'استرداد اشتراك دورة إدارة',
      student: 'محمود طارق',
      type: 'course',
      totalAmount: 150.0,
      instructorShare: 105.0,
      platformShare: 45.0,
      status: 'refunded',
    },
  ],
  totalTransactions: 64,
  engagedStudents: [
    {
      id: 'st-1',
      initials: 'AA',
      name: 'أحمد محمد',
      grade: 'السنة الثالثة - كلية الطب',
      lessonsCount: 12,
      totalSpent: 600,
      avatarColor: '#0052CC',
    },
    {
      id: 'st-2',
      initials: 'SH',
      name: 'سارة حسام',
      grade: 'السنة الثانية - كلية الصيدلة',
      lessonsCount: 9,
      totalSpent: 480,
      avatarColor: '#00A980',
    },
    {
      id: 'st-3',
      initials: 'MS',
      name: 'محمد سمير',
      grade: 'السنة الأولى - كلية الطب',
      lessonsCount: 7,
      totalSpent: 360,
      avatarColor: '#FF9F1C',
    },
    {
      id: 'st-4',
      initials: 'NO',
      name: 'نور الهدى عادل',
      grade: 'السنة الثالثة - كلية الصيدلة',
      lessonsCount: 6,
      totalSpent: 320,
      avatarColor: '#9333EA',
    },
    {
      id: 'st-5',
      initials: 'MT',
      name: 'محمود طارق',
      grade: 'السنة الثانية - كلية الطب',
      lessonsCount: 5,
      totalSpent: 275,
      avatarColor: '#0EA5E9',
    },
  ],
  teachingEfficiency: {
    avgLessonDurationMinutes: 58,
    lessonsPerStudent: 3.4,
    rebookingRate: 0.6,
    completionRate: 91,
    cancellationRate: 6.2,
    cancellationTarget: 8,
    ratingAverage: 4.92,
    ratingCount: 84,
    instructorName: 'د. أحمد حسان',
    instructorId: '#LEC-44029',
  },
};