import type { InstructorDashboardData } from './types';

export const MOCK_INSTRUCTOR_DASHBOARD: InstructorDashboardData = {
  instructorName: 'د. أحمد',
  kpis: {
    activeCourses: 42,
    pendingReviewCourses: 3,
    enrolledStudents: 286,
    monthlyStudentsGrowth: 12,
    upcomingLessons: 8,
    todayLessonsCount: 3,
    monthlyEarnings: 3680,
    instructorSharePercentage: 70,
  },
  upcomingLessons: [
    {
      id: '1',
      studentName: 'أحمد علي',
      studentGrade: 'الصف الثاني عشر',
      avatarInitials: 'أع',
      avatarColor: '#EFF6FF',
      subject: 'أحمد علي',
      dateTime: '14 سبتمبر 2026',
      timeNote: '10:00 صباحاً (خلال 45 دقيقة)',
      duration: '60 دقيقة',
      status: 'upcoming',
      statusText: 'قادم',
      canJoin: true,
    },
    {
      id: '2',
      studentName: 'محمد سمير',
      studentGrade: 'تفاضل وتكامل 2',
      avatarInitials: 'مس',
      avatarColor: '#FDF2F8',
      subject: 'اناتومي',
      dateTime: '14 سبتمبر 2026',
      timeNote: '01:00 مساءً',
      duration: '60 دقيقة',
      status: 'upcoming',
      statusText: 'قادم',
      canJoin: true,
    },
    {
      id: '3',
      studentName: 'سارة حسن',
      studentGrade: 'السنة التمهيدية',
      avatarInitials: 'سح',
      avatarColor: '#FFFBEB',
      subject: 'باطنة',
      dateTime: '15 سبتمبر 2026',
      timeNote: '11:00 صباحاً',
      duration: '45 دقيقة',
      status: 'upcoming',
      statusText: 'قادم',
      canJoin: false,
    },
    {
      id: '4',
      studentName: 'سارة حسن',
      studentGrade: 'السنة التمهيدية',
      avatarInitials: 'سح',
      avatarColor: '#FFFBEB',
      subject: 'تشريح',
      dateTime: '15 سبتمبر 2026',
      timeNote: '11:00 صباحاً',
      duration: '45 دقيقة',
      status: 'upcoming',
      statusText: 'قادم',
      canJoin: false,
    },
    {
      id: '5',
      studentName: 'سارة حسن',
      studentGrade: 'السنة التمهيدية',
      avatarInitials: 'سح',
      avatarColor: '#FFFBEB',
      subject: 'رمد',
      dateTime: '15 سبتمبر 2026',
      timeNote: '11:00 صباحاً',
      duration: '45 دقيقة',
      status: 'upcoming',
      statusText: 'قادم',
      canJoin: false,
    },
  ],
  todayScheduleDate: 'الإثنين، 14 سبتمبر 2026',
  todaySchedule: [
    {
      id: 'slot-1',
      time: '09:00 ص',
      isBooked: false,
      statusText: 'فترة شاغرة',
    },
    {
      id: 'slot-2',
      time: '10:00 ص',
      isBooked: true,
      title: 'تشريح',
      attendee: 'أحمد علي',
      duration: '60 دقيقة',
      statusText: 'محجوز',
    },
    {
      id: 'slot-3',
      time: '12:00 م',
      isBooked: false,
      statusText: 'فترة شاغرة',
    },
    {
      id: 'slot-4',
      time: '01:00 م',
      isBooked: true,
      title: 'باطنة',
      attendee: 'محمد سمير',
      duration: '60 دقيقة',
      statusText: 'محجوز',
    },
    {
      id: 'slot-5',
      time: '03:00 م',
      isBooked: false,
      statusText: 'فترة شاغرة',
    },
  ],
  coursesTotalCount: 42,
  courses: [
    {
      id: 'course-1',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'active',
      statusText: 'نشط',
      lastUpdated: '27 أغسطس 2026',
    },
    {
      id: 'course-2',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'under_review',
      statusText: 'قيد المراجعة',
      lastUpdated: '27 أغسطس 2026',
    },
    {
      id: 'course-3',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'rejected',
      statusText: 'مرفوض',
      lastUpdated: '27 أغسطس 2026',
    },
    {
      id: 'course-4',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'active',
      statusText: 'نشط',
      lastUpdated: '27 أغسطس 2026',
    },
  ],
  earnings: {
    totalRevenue: 5240,
    instructorShare: 3668,
    instructorPercentage: 70,
    platformShare: 1572,
    platformPercentage: 30,
  },
  weeklyAvailability: [
    {
      dayName: 'الإثنين',
      timeRange: '09:00 ص – 01:00 م',
    },
    {
      dayName: 'الثلاثاء',
      timeRange: '02:00 م – 06:00 م',
    },
    {
      dayName: 'الأربعاء',
      timeRange: '09:00 ص – 12:00 م',
    },
    {
      dayName: 'الخميس',
      timeRange: '02:00 م – 06:00 م',
    },
    {
      dayName: 'الجمعة',
      isUnavailable: true,
    },
  ],
};
