import {
  StudentItem,
  StudentEnrolledCourse,
  StudentOrderPayment,
  StudentCourseProgressData,
} from 'src/types/student';

export const MOCK_STUDENTS: StudentItem[] = [
  {
    id: 'stu-1',
    studentCode: 'STU-001284',
    nameAr: 'أحمد محمد علي',
    nameEn: 'Ahmed Mohamed Ali',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 8,
    progressPercent: 72,
    isActive: true,
    country: 'جمهورية مصر العربية 🇪🇬',
    city: 'القاهرة، مصر',
    university: 'جامعة القاهرة (القصر العيني)',
    college: 'كلية الطب البشري',
    academicYear: 'السنة الرابعة',
    username: 'ahmed.ali_med',
    email: 'ahmed.ali@med.cu.edu.eg',
    birthDate: '14 سبتمبر 2002 (23 سنة)',
    gender: 'ذكر',
    nationalId: '30209140102938',
    totalCourses: 8,
    completedCourses: 3,
    inProgressCourses: 4,
    totalPaid: '1,250 ج.م',
    pendingReviews: 1,
  },
  {
    id: 'stu-2',
    studentCode: 'STU-001285',
    nameAr: 'أحمد محمد',
    nameEn: 'Ahmed Mohamed',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 8,
    progressPercent: 72,
    isActive: true,
    country: 'جمهورية مصر العربية 🇪🇬',
    city: 'القاهرة، مصر',
    university: 'جامعة عين شمس',
    college: 'كلية الطب البشري',
    academicYear: 'السنة الثالثة',
    username: 'ahmed_m',
    email: 'ahmed.m@med.asu.edu.eg',
    birthDate: '20 أكتوبر 2003 (22 سنة)',
    gender: 'ذكر',
    nationalId: '30310200101928',
    totalCourses: 8,
    completedCourses: 2,
    inProgressCourses: 5,
    totalPaid: '950 ج.م',
    pendingReviews: 0,
  },
  {
    id: 'stu-3',
    studentCode: 'STU-001286',
    nameAr: 'فارس خالمري موسى',
    nameEn: 'Fares Khalmari Mousa',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 8,
    progressPercent: 72,
    isActive: true,
    country: 'دولة الكويت 🇰🇼',
    city: 'مدينة الكويت',
    university: 'جامعة الكويت',
    college: 'كلية الطب',
    academicYear: 'السنة الخامسة',
    username: 'fares.mousa',
    email: 'fares.mousa@ku.edu.kw',
    birthDate: '05 مايو 2001 (25 سنة)',
    gender: 'ذكر',
    nationalId: '20105050101922',
    totalCourses: 8,
    completedCourses: 4,
    inProgressCourses: 4,
    totalPaid: '340 د.ك',
    pendingReviews: 0,
  },
  {
    id: 'stu-4',
    studentCode: 'STU-001287',
    nameAr: 'أحمد محمد',
    nameEn: 'Ahmed Mohamed',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 8,
    progressPercent: 72,
    isActive: true,
    country: 'المملكة العربية السعودية 🇸🇦',
    city: 'الرياض',
    university: 'جامعة الملك سعود',
    college: 'كلية الطب',
    academicYear: 'السنة الرابعة',
    username: 'ahmed.ksu',
    email: 'ahmed@ksu.edu.sa',
    birthDate: '11 يناير 2002 (24 سنة)',
    gender: 'ذكر',
    nationalId: '10201110291823',
    totalCourses: 6,
    completedCourses: 2,
    inProgressCourses: 4,
    totalPaid: '1,500 ر.س',
    pendingReviews: 1,
  },
  {
    id: 'stu-5',
    studentCode: 'STU-001288',
    nameAr: 'سارة عبد الله الشمري',
    nameEn: 'Sara Abdullah Al-Shammari',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 5,
    progressPercent: 85,
    isActive: false,
    country: 'دولة الكويت 🇰🇼',
    city: 'حولي، الكويت',
    university: 'جامعة الكويت',
    college: 'كلية الصيدلة',
    academicYear: 'السنة الثالثة',
    username: 'sara.shammari',
    email: 'sara.shammari@ku.edu.kw',
    birthDate: '18 أغسطس 2003 (23 سنة)',
    gender: 'أنثى',
    nationalId: '30308180102918',
    totalCourses: 5,
    completedCourses: 4,
    inProgressCourses: 1,
    totalPaid: '280 د.ك',
    pendingReviews: 0,
  },
  {
    id: 'stu-6',
    studentCode: 'STU-001289',
    nameAr: 'محمد كريم منصور',
    nameEn: 'Mohamed Karim Mansour',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 8,
    progressPercent: 72,
    isActive: true,
    country: 'جمهورية مصر العربية 🇪🇬',
    city: 'الإسكندرية، مصر',
    university: 'جامعة الإسكندرية',
    college: 'كلية الطب البشري',
    academicYear: 'السنة الثانية',
    username: 'm.karim',
    email: 'm.karim@med.alexu.edu.eg',
    birthDate: '02 فبراير 2004 (22 سنة)',
    gender: 'ذكر',
    nationalId: '30402020102919',
    totalCourses: 7,
    completedCourses: 2,
    inProgressCourses: 4,
    totalPaid: '850 ج.م',
    pendingReviews: 0,
  },
  {
    id: 'stu-7',
    studentCode: 'STU-001290',
    nameAr: 'نور الدين مصطفى',
    nameEn: 'Nour El-Din Mostafa',
    avatar: '/images/avatar_placeholder.png',
    joinedDate: '05-08-2026',
    phoneNumber: '+965 3132 1222',
    coursesCount: 4,
    progressPercent: 60,
    isActive: false,
    country: 'جمهورية مصر العربية 🇪🇬',
    city: 'المنصورة، مصر',
    university: 'جامعة المنصورة',
    college: 'كلية الطب البشري',
    academicYear: 'السنة الأولى',
    username: 'nour.mostafa',
    email: 'nour@med.mans.edu.eg',
    birthDate: '12 نوفمبر 2005 (20 سنة)',
    gender: 'ذكر',
    nationalId: '30511120102918',
    totalCourses: 4,
    completedCourses: 1,
    inProgressCourses: 3,
    totalPaid: '500 ج.م',
    pendingReviews: 0,
  },
];

export const MOCK_ENROLLED_COURSES: StudentEnrolledCourse[] = [
  {
    id: 'crs-1',
    code: 'CARD',
    title: 'أساسيات تخطيط كهربية القلب (ECG Masterclass)',
    lessonsInfo: '18 وحدة تعليمية • 24 ساعة تدريبية',
    specialization: 'الباطنة / القلب',
    instructor: 'د. شريف حلمي',
    enrollmentDate: '12 أغسطس 2026',
    progressPercent: 75,
    progressText: '14 من 18 درس',
    lastActivity: 'اليوم 09:30 ص',
    status: 'in_progress',
    statusText: 'قيد الدراسة',
  },
  {
    id: 'crs-2',
    code: 'SURG',
    title: 'الجراحة العامة المتقدمة وحالات الطوارئ',
    lessonsInfo: '30 وحدة تعليمية • 45 ساعة تدريبية',
    specialization: 'الجراحة العامة',
    instructor: 'د. محمود سالم',
    enrollmentDate: '05 يوليو 2026',
    progressPercent: 40,
    progressText: '12 من 30 درس',
    lastActivity: 'منذ يومين',
    status: 'in_progress',
    statusText: 'قيد الدراسة',
  },
  {
    id: 'crs-3',
    code: 'PHAR',
    title: 'مقدمة في علم الأدوية السريري (Clinical Pharmacology)',
    lessonsInfo: '12 وحدة تعليمية • 16 ساعة تدريبية',
    specialization: 'الفارماكولوجي',
    instructor: 'د. سارة عثمان',
    enrollmentDate: '10 يونيو 2026',
    progressPercent: 100,
    progressText: 'مكتمل بنجاح ✓',
    lastActivity: '18 يوليو 2026',
    status: 'completed',
    statusText: 'مكتملة',
  },
];

export const MOCK_ORDER_PAYMENTS: StudentOrderPayment[] = [
  {
    id: 'ord-1',
    orderNumber: '#ORD-10245',
    itemTitle: 'أساسيات أمراض القلب والأوعية الدموية',
    amount: '450 ج.م',
    orderDate: '12 أغسطس 2026',
    status: 'under_review',
    statusText: 'قيد المراجعة',
  },
  {
    id: 'ord-2',
    orderNumber: '#ORD-09821',
    itemTitle: 'الجراحة العامة المتقدمة وحالات الطوارئ',
    amount: '500 ج.م',
    orderDate: '05 يوليو 2026',
    status: 'paid_active',
    statusText: 'تم الدفع والتفعيل',
  },
  {
    id: 'ord-3',
    orderNumber: '#ORD-09821',
    itemTitle: 'الجراحة العامة المتقدمة وحالات الطوارئ',
    amount: '500 ج.م',
    orderDate: '05 يوليو 2026',
    status: 'paid_active',
    statusText: 'تم الدفع والتفعيل',
  },
  {
    id: 'ord-4',
    orderNumber: '#ORD-09821',
    itemTitle: 'الجراحة العامة المتقدمة وحالات الطوارئ',
    amount: '500 ج.م',
    orderDate: '05 يوليو 2026',
    status: 'paid_active',
    statusText: 'تم الدفع والتفعيل',
  },
];

export const MOCK_COURSE_PROGRESS: StudentCourseProgressData = {
  courseCode: 'CARD',
  courseTitle: 'أساسيات تخطيط كهربية القلب (ECG Masterclass)',
  statusText: 'قيد الدراسة حالياً',
  studentName: 'أحمد محمد علي',
  studentCode: 'STU-001284',
  instructorName: 'د. شريف حلمي',
  enrollmentDate: '12 أغسطس 2026',
  totalProgressPercent: 75,
  completedLessons: '14 / 18',
  remainingLessonsText: 'متبقى 4 وحدات فقط',
  watchTime: '18.5',
  watchTimeTotal: '24h',
  chapters: [
    {
      id: 'ch-1',
      chapterNumber: 1,
      title: 'الفصل الأول: مقدمة وتشريح الجهاز الكهربي للقلب',
      badgeText: 'مكتمل 100% ✓',
      badgeType: 'completed',
      subtitle: '4 دروس تعليمية • اختبار تقييمي واحد',
      lessons: [
        {
          id: 'les-1-1',
          type: 'video',
          title: '1.1 نظرة عامة على الإشارات الكهربية وانقباض البطين',
          meta: 'فيديو • 25 دقيقة • تمت المشاهدة بالكامل',
          badge: '25m / 25m',
          isCompleted: true,
        },
        {
          id: 'les-1-2',
          type: 'pdf',
          title: '1.2 فسيولوجيا العقدة الجيبية الأذينية (SA Node)',
          meta: 'فيديو • 30 دقيقة • مرفق ملخص PDF (تم تنزيله)',
          badge: '30m / 30m',
          isCompleted: true,
        },
        {
          id: 'les-1-3',
          type: 'quiz',
          title: 'اختبار تقييم الفصل الأول (ECG Basics Assessment)',
          meta: 'تاريخ الاجتياز: 14 أغسطس 2026',
          badge: 'تم الاجتياز',
          isCompleted: true,
        },
      ],
    },
    {
      id: 'ch-2',
      chapterNumber: 2,
      title: 'الفصل الثاني: تخطيط القلب والنبضات غير الطبيعية (Arrhythmias)',
      badgeText: 'قيد الدراسة (65%)',
      badgeType: 'in_progress',
      subtitle: '6 دروس تعليمية • اختبار نصف دورة',
      lessons: [
        {
          id: 'les-2-1',
          type: 'video',
          title: '2.1 تسارع نبضات القلب البطيني (Ventricular Tachycardia)',
          meta: 'فيديو • 40 دقيقة • توقف عند الدقيقة 28:14',
          badge: '28m / 40m',
          isCompleted: false,
          progressPercent: 70,
          stoppedAt: '28:14',
        },
        {
          id: 'les-2-2',
          type: 'article',
          title: '2.2 تشخيص الجلطات الحادة من خلال موجة ST',
          meta: 'مقال سريري ودراسة حالة • 20 دقيقة',
          badge: 'قيد القراءة',
          isCompleted: false,
        },
        {
          id: 'les-2-3',
          type: 'article',
          title: '2.3 تشخيص الجلطات الحادة من خلال موجة ST',
          meta: 'مقال سريري ودراسة حالة • 20 دقيقة',
          badge: 'قيد القراءة',
          isCompleted: false,
        },
      ],
    },
  ],
};
