import type { InstructorDashboardData } from './types';

export const MOCK_INSTRUCTOR_DASHBOARD: InstructorDashboardData = {
  instructorName: 'د. أحمد',
  kpis: {
    activeCourses: 42,
    pendingReviewCourses: 3,
    enrolledStudents: 286,
    monthlyStudentsGrowth: 12,
    monthlyEarnings: 3680,
    instructorSharePercentage: 70,
  },
  attention: {
    pendingTasksCount: 3,
    items: [
      {
        id: 'pending_review',
        count: 24,
        title: 'دورات بانتظار المراجعة',
        description: 'بانتظار موافقة الادمن وتحتاج إلى المراجعة قبل النشر للطلاب.',
        badgeBg: '#FEF3C7',
        badgeColor: '#D97706',
        borderColor: '#FDE68A',
        buttonText: 'مراجعة الدورات',
        buttonVariant: 'amber',
        actionType: 'pending_review',
      },
      {
        id: 'accepted',
        count: 18,
        title: 'الدورات المقبولة',
        description: 'تم تأكيد الدورة من قبل الادمن وتم نشر الدورة للطلاب',
        badgeBg: '#FEF3C7',
        badgeColor: '#D97706',
        borderColor: '#E2E8F0',
        buttonText: 'مراجعة الدورات',
        buttonVariant: 'emerald',
        actionType: 'accepted',
      },
      {
        id: 'rejected',
        count: 7,
        title: 'دورات مرفوضة',
        description: 'دورات تحتاج إلى متابعة لمعرفة سبب الرفض واستكمال النواقص.',
        badgeBg: '#FEE2E2',
        badgeColor: '#DC2626',
        borderColor: '#FECACA',
        buttonText: 'عرض الدورات',
        buttonVariant: 'subtle',
        actionType: 'rejected',
      },
    ],
  },
  courseStatus: {
    totalCount: 856,
    items: [
      { label: 'منشورة', count: 742, percentage: 86.7, color: '#00A76F' },
      { label: 'قيد مراجعة الإدارة', count: 24, percentage: 2.8, color: '#F59E0B' },
      { label: 'مرفوضة / بحاجة لتعديل', count: 21, percentage: 2.5, color: '#EF4444' },
    ],
  },
  studentGrowth: {
    newStudentsCount: 840,
    growthPercentage: 8.5,
    dataPoints: [
      { month: 'يناير', count: 420 },
      { month: 'فبراير', count: 560 },
      { month: 'مارس', count: 610 },
      { month: 'أبريل', count: 720 },
      { month: 'مايو', count: 680 },
      { month: 'يونيو', count: 790 },
      { month: 'يوليو', count: 810 },
      { month: 'أغسطس', count: 840, isCurrent: true },
    ],
  },
  coursesTotalCount: 42,
  courses: [
    {
      id: 'course-1',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'active',
      statusText: 'نشط',
      lastUpdated: '27 أغسطس 2026',
    },
    {
      id: 'course-2',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'under_review',
      statusText: 'قيد المراجعة',
      lastUpdated: '27 أغسطس 2026',
    },
    {
      id: 'course-3',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'rejected',
      statusText: 'مرفوض',
      lastUpdated: '27 أغسطس 2026',
    },
    {
      id: 'course-4',
      title: 'اساسيات امراض القلب',
      specialization: 'امراض القلب',
      studentsCount: '1.245',
      rating: 4.8,
      price: 150,
      status: 'active',
      statusText: 'نشط',
      lastUpdated: '27 أغسطس 2026',
    },
  ],
  earnings: {
    totalRevenue: 5240,
    instructorShare: 3668,
    instructorPercentage: 70,
    platformShare: 1572,
    platformPercentage: 30,
  },
};
